export const CONTENT_TYPES = {
    APPLICATION_JSON: 'application/json',
    FORM: 'x-www-form',
    OTHER: 'raw',
    XML: 'xml',
    NONE: 'none',
};
export const CAPTURE_TYPES = {
    XPATH: 'XPath',
    JSON_PATH: 'JSONPath',
};
export const CAPTURE_TYPE_TO_REQUEST={
    [CAPTURE_TYPES.XPATH]:'xpath',
    [CAPTURE_TYPES.JSON_PATH]:'json',

};
export const CAPTURE_RES_TYPE_TO_CAPTURE_TYPE={
    json:CAPTURE_TYPES.JSON_PATH,
    xpath:CAPTURE_TYPES.XPATH
}
export const SUPPORTED_CONTENT_TYPES = [CONTENT_TYPES.NONE,CONTENT_TYPES.FORM, CONTENT_TYPES.APPLICATION_JSON, CONTENT_TYPES.OTHER];
export const SUPPORTED_CAPTURE_TYPES = [CAPTURE_TYPES.JSON_PATH, CAPTURE_TYPES.XPATH];
export const HTTP_METHODS = ['POST', 'GET', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD', 'CONNECT', 'TRACE'];
