export const GET_REPORTS = 'GET_REPORTS';
export const GET_LAST_REPORTS = 'GET_LAST_REPORTS';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAILURE = 'GET_REPORTS_FAILURE';
export const CLEAR_ERROR_ON_GET_REPORTS = 'CLEAR_ERROR_ON_GET_REPORTS';

export const GET_REPORT = 'GET_REPORT';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAILURE = 'GET_REPORT_FAILURE';

export const CLEAR_SELECTED_REPORT = 'CLEAR_SELECTED_REPORT';
export const CLEAR_REPORTS = 'CLEAR_REPORTS';
export const PROCESSING_GET_REPORTS = 'PROCESSING_GET_REPORTS';

export const GET_AGGREGATE_REPORT = 'GET_AGGREGATE_REPORT';
export const GET_AGGREGATE_REPORT_SUCCESS = 'GET_AGGREGATE_REPORT_SUCCESS';
export const GET_AGGREGATE_REPORT_FAILURE = 'GET_AGGREGATE_REPORT_FAILURE';

