apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-auth
data:
  DATABASE_PASSWORD: {{ .Values.DATABASE_PASSWORD }}
  DATABASE_USERNAME: {{ .Values.DATABASE_USERNAME }}