{
 "title": "Predator",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "some-cluster" },
   {
    "name": "Name",
    "label": "Name",
    "query": "label_values(runnerStats, testName)"
   }
  ]
 },
 "panels": [
  {
   "title": "0.9 Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(request_duration_seconds_bucket{testName=\"$Name\", job=\"$Cluster\"}[60s])) by (le, status_code, path))",
     "legendFormat": "{{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(request_duration_seconds_count{testName=\"$Name\", job=\"$Cluster\"}[60s])) by (status_code, path))",
     "legendFormat": "{{path}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(runnerStats{testName=\"$Name\", job=\"$Cluster\", field=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(runnerStats{testName=\"Gett Scenario - correct before definitions\", field=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{testName=\"$Name\", job=\"$Cluster\"}[60s])) by (le))"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{testName=\"$Name\", job=\"$Cluster\"}[30s])) / 30"
    }
   ]
  },
  {
   "title": "Avoided Scenarios",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(runnerStats{testName=\"$Name\", job=\"$Cluster\", field=\"avoidedScenarios\"})",
     "legendFormat": "Avoided Scenarios"
    }
   ]
  },
  {
   "title": "Pending Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(runnerStats{testName=\"$Name\", job=\"$Cluster\", field=\"pendingRequests\"})",
     "legendFormat": "pendingRequests"
    }
   ]
  }
 ]
}