
export const GET_CHAOS_EXPERIMENTS = 'GET_CHAOS_EXPERIMENTS';
export const GET_CHAOS_EXPERIMENTS_SUCCESS = 'GET_CHAOS_EXPERIMENTS_SUCCESS';
export const GET_CHAOS_EXPERIMENTS_FAILURE = 'GET_CHAOS_EXPERIMENTS_FAILURE';

export const CREATE_CHAOS_EXPERIMENT = 'CREATE_CHAOS_EXPERIMENT';
export const CREATE_CHAOS_EXPERIMENT_SUCCESS = 'CREATE_CHAOS_EXPERIMENT_SUCCESS';
export const CREATE_CHAOS_EXPERIMENT_FAILURE = 'CREATE_CHAOS_EXPERIMENT_FAILURE';

export const UPDATE_CHAOS_EXPERIMENT = 'UPDATE_CHAOS_EXPERIMENT';
export const UPDATE_CHAOS_EXPERIMENT_SUCCESS = 'UPDATE_CHAOS_EXPERIMENT_SUCCESS';
export const UPDATE_CHAOS_EXPERIMENT_FAILURE = 'UPDATE_CHAOS_EXPERIMENT_FAILURE';

export const DELETE_CHAOS_EXPERIMENT = 'DELETE_CHAOS_EXPERIMENT';
export const DELETE_CHAOS_EXPERIMENT_SUCCESS = 'DELETE_CHAOS_EXPERIMENT_SUCCESS';
export const DELETE_CHAOS_EXPERIMENT_FAILURE = 'DELETE_CHAOS_EXPERIMENT_FAILURE';

export const CHAOS_EXPERIMENTS_LOADING = 'CHAOS_EXPERIMENTS_LOADING';
export const CLEAN_ALL_ERRORS = 'CLEAN_ALL_ERRORS';
