
export const GET_PROCESSORS = 'GET_PROCESSORS';
export const GET_PROCESSORS_SUCCESS = 'GET_PROCESSORS_SUCCESS';
export const GET_PROCESSORS_FAILURE = 'GET_PROCESSORS_FAILURE';

export const PROCESSORS_LOADING = 'PROCESSORS_LOADING';

export const CLEAN_ALL_ERRORS = 'CLEAN_ALL_ERRORS';


