import { initCreateTestForm,editTest,cleanAllErrors,clearDeleteTestSuccess, deleteTest, deleteTestFailure, deleteTestSuccess, clearErrorOnDeleteTest, getTests, getTestsSuccess, getTestFaliure, chooseTest, processingGetTests, clearSelectedTest, clearErrorOnGetTests, clearTests, getTestsFaliure, getTestSuccess,createTest } from './actions/testsActions';
import { clearStopJobSuccess, clearDeleteJobSuccess, deleteJob, deleteJobFailure, deleteJobSuccess, clearErrorOnDeleteJob, clearErrorOnStopJob, stopRunningJob, stopRunningJobSuccess, stopRunningJobFailure, createJobSuccess, createJobFailure, processingCreateJob, clearErrorOnCreateJob, createJob, getJobsFaliure, processingGetJobs, getJobsSuccess, getJobs, getJob, clearErrorOnGetJobs, clearJobs, clearSelectedJob, getJobFaliure, getJobSuccess } from './actions/jobsActions';
import { getLastReports, getReport, clearErrorOnGetReports, clearReports, clearSelectedReport, getReportFaliure, getReports, getReportsFaliure, getReportsSuccess, getReportSuccess, processingGetReports } from './actions/reportsActions';

export {
  // tests//
  initCreateTestForm,
  editTest,
  cleanAllErrors,
  getTests,
  getTestsSuccess,
  getTestFaliure,
  chooseTest,
  processingGetTests,
  clearSelectedTest,
  clearErrorOnGetTests,
  clearTests,
  getTestsFaliure,
  getTestSuccess,
  deleteTest,
  deleteTestSuccess,
  deleteTestFailure,
  clearErrorOnDeleteTest,
  clearDeleteTestSuccess,
  createTest,
  // jobs//
  getJobsFaliure,
  processingGetJobs,
  getJobsSuccess,
  getJobs,
  getJob,
  clearErrorOnGetJobs,
  clearJobs,
  clearSelectedJob,
  getJobFaliure,
  getJobSuccess,
  createJobFailure,
  processingCreateJob,
  clearErrorOnCreateJob,
  createJob,
  createJobSuccess,
  stopRunningJob,
  stopRunningJobSuccess,
  stopRunningJobFailure,
  clearErrorOnStopJob,
  deleteJob,
  deleteJobSuccess,
  deleteJobFailure,
  clearErrorOnDeleteJob,
  clearDeleteJobSuccess,
  clearStopJobSuccess,

  // reports//
  getReport,
  clearErrorOnGetReports,
  clearReports,
  clearSelectedReport,
  getReportFaliure,
  getReports,
  getReportsFaliure,
  getReportsSuccess,
  getReportSuccess,
  processingGetReports,
  getLastReports
};
